SimpleCov.start do
  add_filter "/features/"
  add_filter "/spec/"
  add_group "actions", "lib/puppet_generator/actions/"
  add_group "api", "lib/puppet_generator/api/"
  add_group "defaults", "lib/puppet_generator/defaults/"
  add_group "entry_converters", "lib/puppet_generator/entry_converters/"
  add_group "exporter_filters", "lib/puppet_generator/export_filters/"
  add_group "exporters", "lib/puppet_generator/exporters/"
  add_group "import_filters", "lib/puppet_generator/import_filters/"
  add_group "importers", "lib/puppet_generator/importers/"
  add_group "middleware", "lib/puppet_generator/middleware/"
  add_group "models", "lib/puppet_generator/models/"
  add_group "output_objects", "lib/puppet_generator/output_objects/"
  add_group "setups", "lib/puppet_generator/setups/"
  add_group "ui", "lib/puppet_generator/ui/"
end
