require 'erb'
require 'erubis'
require 'middleware'
require 'find'
require 'logger'
require 'pathname'
require 'ansi'

require 'puppet_generator/version'
require 'puppet_generator/input_file'
require 'puppet_generator/input_directory'
require 'puppet_generator/input_stdin'
require 'puppet_generator/exceptions'
require 'puppet_generator/output_directory'
require 'puppet_generator/output_file'
require 'puppet_generator/output_stdout'

require 'puppet_generator/puppet_package'
require 'puppet_generator/puppet_file'
require 'puppet_generator/templates/class_package'
require 'puppet_generator/templates/single_package'
require 'puppet_generator/templates/class_file'
require 'puppet_generator/templates/single_file'
require 'puppet_generator/definition'
require 'puppet_generator/task'
require 'puppet_generator/actions/handle_errors'
require 'puppet_generator/actions/check_for_empty_source'
require 'puppet_generator/actions/read_input'
require 'puppet_generator/actions/entry_to_package'
require 'puppet_generator/actions/entry_to_file'
require 'puppet_generator/actions/determine_templates'
require 'puppet_generator/actions/create_output'
require 'puppet_generator/api'


module PuppetGenerator
end
