#!/usr/bin/env ruby

require 'tmrb'

tmux = TmRb::Multiplexer.new
#creates an empty window
tmux.new_session(:session_name => "puppet_generator")

tmux.new_window(:name => 'lib', :command => 'vim -c \"NERDTree lib/puppet_generator/\"')
tmux.new_window(:name => 'middleware', :command => 'vim -c  \"NERDTree lib/puppet_generator/middleware\"')
tmux.new_window(:name => 'templates', :command => 'vim -c  \"NERDTree templates/\"')
tmux.new_window(:name => 'actions', :command => 'vim -c  \"NERDTree lib/puppet_generator/actions/\"')
tmux.new_window(:name => 'filter', :command => 'vim -c  \"NERDTree lib/puppet_generator/filter\"')
tmux.new_window(:name => 'spec', :command => 'vim -c \"NERDTree spec\"')
tmux.new_window(:name => 'features', :command => 'vim -c \"NERDTree features\"')
tmux.start
