#!/usr/bin/env ruby

require 'tmrb'

tmux = TmRb::Multiplexer.new
#creates an empty window
tmux.new_session(:session_name => "puppet_generator")

tmux.new_window(:name => 'lib', :command => 'vim -c "NERDTree lib/*.rb"')
tmux.new_window(:name => 'actions', :command => 'vim -c  "NERDTree lib/actions/*.rb"')
tmux.new_window(:name => 'templates', :command => 'vim -c  "NERDTree lib/templates/*.rb"')
tmux.new_window(:name => 'filter', :command => 'vim -c  "NERDTree lib/filter/*.rb"')
tmux.new_window(:name => 'spec', :command => 'vim -c "NERDTree spec/**/*.rb"')
tmux.new_window(:name => 'features', :command => 'vim -p features/**/*.{rb,feature}')
tmux.start
